### ISSUE TITLE
☂️ Release v2

### ISSUE THREAD

**Issue by NickVolynkin** [qase-tms/qase-javascript#531]
Preparing the v2 release of Qase JavaScript reporters

# qaseio and qase-javascript-commons

Package qaseio is the API client and qase-javascript-commons holds common logic that reporters can reuse.

- [ ] #523
- [ ] #525 
- [ ] #526
- [ ] #528 
- [ ] #529 
- [ ] #534
- [x] #536

# Playwright

- [ ] #530
- [ ] Make a tutorial on starting with Playwright from scratch
- [ ] Make a tutorial on starting with existing Playwright tests
- [ ] Make examples of new Playwright syntax and configuration
- [ ] Write a guide on migration from v1

# QA and CI/CD practices

- [ ] Start running CI on examples
- [ ] Rename branch [v2-beta](https://github.com/qase-tms/qase-javascript/tree/v2-beta) to main
- [ ] Start building and testing on Node.js v20 https://nodejs.org/en/about/previous-releases
